<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>LogLeak.PackageConsumer</AssemblyName>
    <RootNamespace>LogLeak.PackageConsumer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KeelMatrix.LogLeak" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
